### ISSUE TITLE
Throws “undefined method `url`”

### ISSUE THREAD

**Issue by jp-montilla** [zooppa/administrate-field-carrierwave#14]
How can I fix this 

**undefined method `url' for "#<ActionDispatch::Http::UploadedFile:0x00007fe2eec4ed10>":String**

The error points to the rendering of the attribute

```
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% end -%>
          </td>
        <% end %>
```

and throws this error in the show page
**undefined method `filename' for "#<ActionDispatch::Http::UploadedFile:0x00007fe2eec4ed10>":String**

**Dashboard**
`profile_picture: Field::Carrierwave.with_options( image: :standard, multiple: false, remove: false, remote_url: false )`

**Comment by michelegera** [comment]
Hi @newbiedetected, this is weird. It looks like your uploaded file is a string rather than an object – that’s what I can infer from the error message, and that’s why the gem is throwing an error: it tries to access the method named `url`, but that’s not defined for a string.

Can you please double-check that the Carrierwave uploader for `profile_picture` in your application (i.e. the class that handles the upload and inherits from `CarrierWave::Uploader::Base`) is correctly set up?

**Comment by jp-montilla** [comment]
It seems that there's an error in saving the file. Anyway I fixed it now.
